# Generated by Django 5.1 on 2024-09-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promociones',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
